version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/delete_node_modules.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
      runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 3600
