version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 3600
